name: dart_up
version: 0.0.0
description: Dart Web application container; run multiple apps in one VM.
environment:
  sdk: ">=2.0.0 <3.0.0"
dependencies:
  angel_client: ^2.0.0
  angel_framework: ^2.0.0
  args: ^1.0.0
  body_parser: ^1.0.0
  cli_util: ^0.1.3
  dbcrypt: ^1.0.0
  http: ^0.12.0
  http_parser: ^3.0.0
  io: ^0.3.2
  json_annotation: ^3.0.0
  json_rpc_2: ^2.0.0
  logging: ^0.11.0
  path: ^1.0.0
  pretty_logging: ^1.0.0
  prompts: ^1.0.0
  pubspec_parse: ^0.1.5
  stream_channel: ^2.0.0
  yaml: ^2.0.0
dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.0.0
  pedantic: ^1.0.0
dependency_overrides:
  analyzer: 0.38.2
executables:
  dart_up: dart_up
